### ISSUE TITLE
Mooshrooms don't spawn with spawners

### ISSUE THREAD

**Issue by bentorre** [ContinentalMC/OLD-Issue-Tracker#2]
When I broke a spawner with silk touch, i placed it back and used a mooshroom spawn egg to change the mob. The spawner went through multiple cycles but never spawned anything

**Comment by Ashparty** [comment]
Did you check the spawn conditions?

**Comment by bentorre** [comment]
It also stopped working with cows too for some reason. Also, what are the spawn conditions for the spawners?

**Comment by Ashparty** [comment]
> It also stopped working with cows too for some reason. Also, what are the spawn conditions for the spawners?

Some spawners have certain blocks they need to spawn mobs on, you can see it by hovering over the mob-head in the bottom left (for cows, they need grass blocks, not sure about mooshrooms)
