### ISSUE TITLE
TownyChat Needs to be Set up

### ISSUE THREAD

**Issue by Party-External** [ContinentalMC/OLD-Issue-Tracker#5]

**Comment by Party-External** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set town/nation names to be visible in chat OR tab](https://trello.com/c/BInLNU8T/62-set-town-nation-names-to-be-visible-in-chat-or-tab)

**Comment by Party-External** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Towny/Nation chat](https://trello.com/c/QXjCU5Md/34-towny-nation-chat)

**Comment by Ashparty** [comment]
Done!
